matrix:
  include:
    - language: node_js
      node_js:
        - "stable"

      script:
        - npm test
        - npm run build

      before_deploy:
        - mkdir -p before-frontend-deploy
        - cp -r build before-frontend-deploy

      deploy:
        - provider: s3
          access_key_id: $ACCESS_KEY_ID
          secret_access_key: $SECRET_ACCESS_KEY
          bucket: wellbell.co.kr
          region: ap-northeast-2
          skip_cleanup: true
          acl: private
          local_dir: before-frontend-deploy/build/
          wait-until-deployed: true