matrix:
  include:
    - language: node_js
      node_js:
        - "stable"

      before_install:
        - cd front-end/

      script:
        - npm test
        - npm run build

      before_deploy:
        - mkdir -p before-frontend-deploy
        - cp scripts/*.sh before-frontend-deploy/
        - cp appspec.yml before-frontend-deploy/
        - cp -r build before-frontend-deploy
        - cd before-frontend-deploy && zip -r before-frontend-deploy *
        - cd ../ && mkdir -p deploy-frontend
        - mv before-frontend-deploy/before-frontend-deploy.zip deploy-frontend/front-end.zip

      deploy:
        - provider: s3
          access_key_id: $ACCESS_KEY_ID
          secret_access_key: $SECRET_ACCESS_KEY
          bucket: myintroduce-springboot-build
          region: ap-northeast-2
          skip_cleanup: true
          acl: private
          local_dir: deploy-frontend
          wait-until-deployed: true

        - provider: codedeploy
          access_key_id: $ACCESS_KEY_ID
          secret_access_key: $SECRET_ACCESS_KEY
          bucket: myintroduce-springboot-build
          key: front-end.zip
          bundle_type: zip
          application: myintroduce-react-service
          deployment_group: myintroduce-react-service-group
          region: ap-northeast-2
          wait-until-deployed: true